//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsServiceNamespace
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://ParsGreen.com/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://ParsGreen.com/", ItemName="int")]
    public class ArrayOfInt : System.Collections.Generic.List<int>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ParsGreen.com/", ConfigurationName="SmsServiceNamespace.SendSMSSoap")]
    public interface SendSMSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/SendOtp", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsServiceNamespace.SendOtpResponse> SendOtpAsync(SmsServiceNamespace.SendOtpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/MessageInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsServiceNamespace.MessageInfoResponse> MessageInfoAsync(SmsServiceNamespace.MessageInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/SendGroupSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsServiceNamespace.SendGroupSMSResponse> SendGroupSMSAsync(SmsServiceNamespace.SendGroupSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/Send", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsServiceNamespace.SendResponse> SendAsync(SmsServiceNamespace.SendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/SendGroupSMSP2P", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsServiceNamespace.SendGroupSMSP2PResponse> SendGroupSMSP2PAsync(SmsServiceNamespace.SendGroupSMSP2PRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/SendToGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsServiceNamespace.SendToGroupResponse> SendToGroupAsync(SmsServiceNamespace.SendToGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/SendGroupSmsSimple", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsServiceNamespace.SendGroupSmsSimpleResponse> SendGroupSmsSimpleAsync(SmsServiceNamespace.SendGroupSmsSimpleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/GetDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsServiceNamespace.GetDeliveryResponse> GetDeliveryAsync(SmsServiceNamespace.GetDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/GetSMSNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsServiceNamespace.GetSMSNumbersResponse> GetSMSNumbersAsync(SmsServiceNamespace.GetSMSNumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOtpRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOtp", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.SendOtpRequestBody Body;
        
        public SendOtpRequest()
        {
        }
        
        public SendOtpRequest(SmsServiceNamespace.SendOtpRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendOtpRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Lang;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int otpType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int patternId;
        
        public SendOtpRequestBody()
        {
        }
        
        public SendOtpRequestBody(string signature, string mobile, string Lang, int otpType, int patternId)
        {
            this.signature = signature;
            this.mobile = mobile;
            this.Lang = Lang;
            this.otpType = otpType;
            this.patternId = patternId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOtpResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOtpResponse", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.SendOtpResponseBody Body;
        
        public SendOtpResponse()
        {
        }
        
        public SendOtpResponse(SmsServiceNamespace.SendOtpResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendOtpResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendOtpResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string otpCode;
        
        public SendOtpResponseBody()
        {
        }
        
        public SendOtpResponseBody(int SendOtpResult, string otpCode)
        {
            this.SendOtpResult = SendOtpResult;
            this.otpCode = otpCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageInfo", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.MessageInfoRequestBody Body;
        
        public MessageInfoRequest()
        {
        }
        
        public MessageInfoRequest(SmsServiceNamespace.MessageInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class MessageInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MsgBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int part;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool isUnicode;
        
        public MessageInfoRequestBody()
        {
        }
        
        public MessageInfoRequestBody(string signature, string MsgBody, int part, bool isUnicode)
        {
            this.signature = signature;
            this.MsgBody = MsgBody;
            this.part = part;
            this.isUnicode = isUnicode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageInfoResponse", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.MessageInfoResponseBody Body;
        
        public MessageInfoResponse()
        {
        }
        
        public MessageInfoResponse(SmsServiceNamespace.MessageInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class MessageInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double MessageInfoResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int part;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool isUnicode;
        
        public MessageInfoResponseBody()
        {
        }
        
        public MessageInfoResponseBody(double MessageInfoResult, int part, bool isUnicode)
        {
            this.MessageInfoResult = MessageInfoResult;
            this.part = part;
            this.isUnicode = isUnicode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendGroupSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendGroupSMS", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.SendGroupSMSRequestBody Body;
        
        public SendGroupSMSRequest()
        {
        }
        
        public SendGroupSMSRequest(SmsServiceNamespace.SendGroupSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendGroupSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SmsServiceNamespace.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isFlash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string udh;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int success;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public SmsServiceNamespace.ArrayOfString retStr;
        
        public SendGroupSMSRequestBody()
        {
        }
        
        public SendGroupSMSRequestBody(string signature, string from, SmsServiceNamespace.ArrayOfString to, string text, bool isFlash, string udh, int success, SmsServiceNamespace.ArrayOfString retStr)
        {
            this.signature = signature;
            this.from = from;
            this.to = to;
            this.text = text;
            this.isFlash = isFlash;
            this.udh = udh;
            this.success = success;
            this.retStr = retStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendGroupSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendGroupSMSResponse", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.SendGroupSMSResponseBody Body;
        
        public SendGroupSMSResponse()
        {
        }
        
        public SendGroupSMSResponse(SmsServiceNamespace.SendGroupSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendGroupSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendGroupSMSResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int success;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SmsServiceNamespace.ArrayOfString retStr;
        
        public SendGroupSMSResponseBody()
        {
        }
        
        public SendGroupSMSResponseBody(int SendGroupSMSResult, int success, SmsServiceNamespace.ArrayOfString retStr)
        {
            this.SendGroupSMSResult = SendGroupSMSResult;
            this.success = success;
            this.retStr = retStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.SendRequestBody Body;
        
        public SendRequest()
        {
        }
        
        public SendRequest(SmsServiceNamespace.SendRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string toMobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string retStr;
        
        public SendRequestBody()
        {
        }
        
        public SendRequestBody(string signature, string toMobile, string smsBody, string retStr)
        {
            this.signature = signature;
            this.toMobile = toMobile;
            this.smsBody = smsBody;
            this.retStr = retStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendResponse", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.SendResponseBody Body;
        
        public SendResponse()
        {
        }
        
        public SendResponse(SmsServiceNamespace.SendResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string retStr;
        
        public SendResponseBody()
        {
        }
        
        public SendResponseBody(int SendResult, string retStr)
        {
            this.SendResult = SendResult;
            this.retStr = retStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendGroupSMSP2PRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendGroupSMSP2P", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.SendGroupSMSP2PRequestBody Body;
        
        public SendGroupSMSP2PRequest()
        {
        }
        
        public SendGroupSMSP2PRequest(SmsServiceNamespace.SendGroupSMSP2PRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendGroupSMSP2PRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SmsServiceNamespace.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public SmsServiceNamespace.ArrayOfString texts;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isFlash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string udh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public SmsServiceNamespace.ArrayOfInt status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public SmsServiceNamespace.ArrayOfInt success;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public SmsServiceNamespace.ArrayOfString retStr;
        
        public SendGroupSMSP2PRequestBody()
        {
        }
        
        public SendGroupSMSP2PRequestBody(string signature, string from, SmsServiceNamespace.ArrayOfString to, SmsServiceNamespace.ArrayOfString texts, bool isFlash, string udh, SmsServiceNamespace.ArrayOfInt status, SmsServiceNamespace.ArrayOfInt success, SmsServiceNamespace.ArrayOfString retStr)
        {
            this.signature = signature;
            this.from = from;
            this.to = to;
            this.texts = texts;
            this.isFlash = isFlash;
            this.udh = udh;
            this.status = status;
            this.success = success;
            this.retStr = retStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendGroupSMSP2PResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendGroupSMSP2PResponse", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.SendGroupSMSP2PResponseBody Body;
        
        public SendGroupSMSP2PResponse()
        {
        }
        
        public SendGroupSMSP2PResponse(SmsServiceNamespace.SendGroupSMSP2PResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendGroupSMSP2PResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendGroupSMSP2PResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SmsServiceNamespace.ArrayOfInt status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SmsServiceNamespace.ArrayOfInt success;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public SmsServiceNamespace.ArrayOfString retStr;
        
        public SendGroupSMSP2PResponseBody()
        {
        }
        
        public SendGroupSMSP2PResponseBody(int SendGroupSMSP2PResult, SmsServiceNamespace.ArrayOfInt status, SmsServiceNamespace.ArrayOfInt success, SmsServiceNamespace.ArrayOfString retStr)
        {
            this.SendGroupSMSP2PResult = SendGroupSMSP2PResult;
            this.status = status;
            this.success = success;
            this.retStr = retStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendToGroupRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendToGroup", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.SendToGroupRequestBody Body;
        
        public SendToGroupRequest()
        {
        }
        
        public SendToGroupRequest(SmsServiceNamespace.SendToGroupRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendToGroupRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string groupIdEncrypt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isFlash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string udh;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int success;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public SmsServiceNamespace.ArrayOfString retStr;
        
        public SendToGroupRequestBody()
        {
        }
        
        public SendToGroupRequestBody(string signature, string from, string groupIdEncrypt, string text, bool isFlash, string udh, int success, SmsServiceNamespace.ArrayOfString retStr)
        {
            this.signature = signature;
            this.from = from;
            this.groupIdEncrypt = groupIdEncrypt;
            this.text = text;
            this.isFlash = isFlash;
            this.udh = udh;
            this.success = success;
            this.retStr = retStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendToGroupResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendToGroupResponse", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.SendToGroupResponseBody Body;
        
        public SendToGroupResponse()
        {
        }
        
        public SendToGroupResponse(SmsServiceNamespace.SendToGroupResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendToGroupResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendToGroupResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int success;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SmsServiceNamespace.ArrayOfString retStr;
        
        public SendToGroupResponseBody()
        {
        }
        
        public SendToGroupResponseBody(int SendToGroupResult, int success, SmsServiceNamespace.ArrayOfString retStr)
        {
            this.SendToGroupResult = SendToGroupResult;
            this.success = success;
            this.retStr = retStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendGroupSmsSimpleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendGroupSmsSimple", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.SendGroupSmsSimpleRequestBody Body;
        
        public SendGroupSmsSimpleRequest()
        {
        }
        
        public SendGroupSmsSimpleRequest(SmsServiceNamespace.SendGroupSmsSimpleRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendGroupSmsSimpleRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SmsServiceNamespace.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isFlash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string udh;
        
        public SendGroupSmsSimpleRequestBody()
        {
        }
        
        public SendGroupSmsSimpleRequestBody(string signature, string from, SmsServiceNamespace.ArrayOfString to, string text, bool isFlash, string udh)
        {
            this.signature = signature;
            this.from = from;
            this.to = to;
            this.text = text;
            this.isFlash = isFlash;
            this.udh = udh;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendGroupSmsSimpleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendGroupSmsSimpleResponse", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.SendGroupSmsSimpleResponseBody Body;
        
        public SendGroupSmsSimpleResponse()
        {
        }
        
        public SendGroupSmsSimpleResponse(SmsServiceNamespace.SendGroupSmsSimpleResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendGroupSmsSimpleResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendGroupSmsSimpleResult;
        
        public SendGroupSmsSimpleResponseBody()
        {
        }
        
        public SendGroupSmsSimpleResponseBody(int SendGroupSmsSimpleResult)
        {
            this.SendGroupSmsSimpleResult = SendGroupSmsSimpleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeliveryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDelivery", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.GetDeliveryRequestBody Body;
        
        public GetDeliveryRequest()
        {
        }
        
        public GetDeliveryRequest(SmsServiceNamespace.GetDeliveryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class GetDeliveryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string recId;
        
        public GetDeliveryRequestBody()
        {
        }
        
        public GetDeliveryRequestBody(string signature, string recId)
        {
            this.signature = signature;
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeliveryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeliveryResponse", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.GetDeliveryResponseBody Body;
        
        public GetDeliveryResponse()
        {
        }
        
        public GetDeliveryResponse(SmsServiceNamespace.GetDeliveryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class GetDeliveryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetDeliveryResult;
        
        public GetDeliveryResponseBody()
        {
        }
        
        public GetDeliveryResponseBody(int GetDeliveryResult)
        {
            this.GetDeliveryResult = GetDeliveryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSMSNumbersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSMSNumbers", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.GetSMSNumbersRequestBody Body;
        
        public GetSMSNumbersRequest()
        {
        }
        
        public GetSMSNumbersRequest(SmsServiceNamespace.GetSMSNumbersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class GetSMSNumbersRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int numberType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SmsServiceNamespace.ArrayOfString numbers;
        
        public GetSMSNumbersRequestBody()
        {
        }
        
        public GetSMSNumbersRequestBody(string signature, int numberType, SmsServiceNamespace.ArrayOfString numbers)
        {
            this.signature = signature;
            this.numberType = numberType;
            this.numbers = numbers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSMSNumbersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSMSNumbersResponse", Namespace="http://ParsGreen.com/", Order=0)]
        public SmsServiceNamespace.GetSMSNumbersResponseBody Body;
        
        public GetSMSNumbersResponse()
        {
        }
        
        public GetSMSNumbersResponse(SmsServiceNamespace.GetSMSNumbersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class GetSMSNumbersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetSMSNumbersResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SmsServiceNamespace.ArrayOfString numbers;
        
        public GetSMSNumbersResponseBody()
        {
        }
        
        public GetSMSNumbersResponseBody(int GetSMSNumbersResult, SmsServiceNamespace.ArrayOfString numbers)
        {
            this.GetSMSNumbersResult = GetSMSNumbersResult;
            this.numbers = numbers;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface SendSMSSoapChannel : SmsServiceNamespace.SendSMSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SendSMSSoapClient : System.ServiceModel.ClientBase<SmsServiceNamespace.SendSMSSoap>, SmsServiceNamespace.SendSMSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SendSMSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SendSMSSoapClient.GetBindingForEndpoint(endpointConfiguration), SendSMSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSMSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SendSMSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSMSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SendSMSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceNamespace.SendOtpResponse> SmsServiceNamespace.SendSMSSoap.SendOtpAsync(SmsServiceNamespace.SendOtpRequest request)
        {
            return base.Channel.SendOtpAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceNamespace.SendOtpResponse> SendOtpAsync(string signature, string mobile, string Lang, int otpType, int patternId)
        {
            SmsServiceNamespace.SendOtpRequest inValue = new SmsServiceNamespace.SendOtpRequest();
            inValue.Body = new SmsServiceNamespace.SendOtpRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.mobile = mobile;
            inValue.Body.Lang = Lang;
            inValue.Body.otpType = otpType;
            inValue.Body.patternId = patternId;
            return ((SmsServiceNamespace.SendSMSSoap)(this)).SendOtpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceNamespace.MessageInfoResponse> SmsServiceNamespace.SendSMSSoap.MessageInfoAsync(SmsServiceNamespace.MessageInfoRequest request)
        {
            return base.Channel.MessageInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceNamespace.MessageInfoResponse> MessageInfoAsync(string signature, string MsgBody, int part, bool isUnicode)
        {
            SmsServiceNamespace.MessageInfoRequest inValue = new SmsServiceNamespace.MessageInfoRequest();
            inValue.Body = new SmsServiceNamespace.MessageInfoRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.MsgBody = MsgBody;
            inValue.Body.part = part;
            inValue.Body.isUnicode = isUnicode;
            return ((SmsServiceNamespace.SendSMSSoap)(this)).MessageInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceNamespace.SendGroupSMSResponse> SmsServiceNamespace.SendSMSSoap.SendGroupSMSAsync(SmsServiceNamespace.SendGroupSMSRequest request)
        {
            return base.Channel.SendGroupSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceNamespace.SendGroupSMSResponse> SendGroupSMSAsync(string signature, string from, SmsServiceNamespace.ArrayOfString to, string text, bool isFlash, string udh, int success, SmsServiceNamespace.ArrayOfString retStr)
        {
            SmsServiceNamespace.SendGroupSMSRequest inValue = new SmsServiceNamespace.SendGroupSMSRequest();
            inValue.Body = new SmsServiceNamespace.SendGroupSMSRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.text = text;
            inValue.Body.isFlash = isFlash;
            inValue.Body.udh = udh;
            inValue.Body.success = success;
            inValue.Body.retStr = retStr;
            return ((SmsServiceNamespace.SendSMSSoap)(this)).SendGroupSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceNamespace.SendResponse> SmsServiceNamespace.SendSMSSoap.SendAsync(SmsServiceNamespace.SendRequest request)
        {
            return base.Channel.SendAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceNamespace.SendResponse> SendAsync(string signature, string toMobile, string smsBody, string retStr)
        {
            SmsServiceNamespace.SendRequest inValue = new SmsServiceNamespace.SendRequest();
            inValue.Body = new SmsServiceNamespace.SendRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.toMobile = toMobile;
            inValue.Body.smsBody = smsBody;
            inValue.Body.retStr = retStr;
            return ((SmsServiceNamespace.SendSMSSoap)(this)).SendAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceNamespace.SendGroupSMSP2PResponse> SmsServiceNamespace.SendSMSSoap.SendGroupSMSP2PAsync(SmsServiceNamespace.SendGroupSMSP2PRequest request)
        {
            return base.Channel.SendGroupSMSP2PAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceNamespace.SendGroupSMSP2PResponse> SendGroupSMSP2PAsync(string signature, string from, SmsServiceNamespace.ArrayOfString to, SmsServiceNamespace.ArrayOfString texts, bool isFlash, string udh, SmsServiceNamespace.ArrayOfInt status, SmsServiceNamespace.ArrayOfInt success, SmsServiceNamespace.ArrayOfString retStr)
        {
            SmsServiceNamespace.SendGroupSMSP2PRequest inValue = new SmsServiceNamespace.SendGroupSMSP2PRequest();
            inValue.Body = new SmsServiceNamespace.SendGroupSMSP2PRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.texts = texts;
            inValue.Body.isFlash = isFlash;
            inValue.Body.udh = udh;
            inValue.Body.status = status;
            inValue.Body.success = success;
            inValue.Body.retStr = retStr;
            return ((SmsServiceNamespace.SendSMSSoap)(this)).SendGroupSMSP2PAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceNamespace.SendToGroupResponse> SmsServiceNamespace.SendSMSSoap.SendToGroupAsync(SmsServiceNamespace.SendToGroupRequest request)
        {
            return base.Channel.SendToGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceNamespace.SendToGroupResponse> SendToGroupAsync(string signature, string from, string groupIdEncrypt, string text, bool isFlash, string udh, int success, SmsServiceNamespace.ArrayOfString retStr)
        {
            SmsServiceNamespace.SendToGroupRequest inValue = new SmsServiceNamespace.SendToGroupRequest();
            inValue.Body = new SmsServiceNamespace.SendToGroupRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.from = from;
            inValue.Body.groupIdEncrypt = groupIdEncrypt;
            inValue.Body.text = text;
            inValue.Body.isFlash = isFlash;
            inValue.Body.udh = udh;
            inValue.Body.success = success;
            inValue.Body.retStr = retStr;
            return ((SmsServiceNamespace.SendSMSSoap)(this)).SendToGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceNamespace.SendGroupSmsSimpleResponse> SmsServiceNamespace.SendSMSSoap.SendGroupSmsSimpleAsync(SmsServiceNamespace.SendGroupSmsSimpleRequest request)
        {
            return base.Channel.SendGroupSmsSimpleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceNamespace.SendGroupSmsSimpleResponse> SendGroupSmsSimpleAsync(string signature, string from, SmsServiceNamespace.ArrayOfString to, string text, bool isFlash, string udh)
        {
            SmsServiceNamespace.SendGroupSmsSimpleRequest inValue = new SmsServiceNamespace.SendGroupSmsSimpleRequest();
            inValue.Body = new SmsServiceNamespace.SendGroupSmsSimpleRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.text = text;
            inValue.Body.isFlash = isFlash;
            inValue.Body.udh = udh;
            return ((SmsServiceNamespace.SendSMSSoap)(this)).SendGroupSmsSimpleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceNamespace.GetDeliveryResponse> SmsServiceNamespace.SendSMSSoap.GetDeliveryAsync(SmsServiceNamespace.GetDeliveryRequest request)
        {
            return base.Channel.GetDeliveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceNamespace.GetDeliveryResponse> GetDeliveryAsync(string signature, string recId)
        {
            SmsServiceNamespace.GetDeliveryRequest inValue = new SmsServiceNamespace.GetDeliveryRequest();
            inValue.Body = new SmsServiceNamespace.GetDeliveryRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.recId = recId;
            return ((SmsServiceNamespace.SendSMSSoap)(this)).GetDeliveryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceNamespace.GetSMSNumbersResponse> SmsServiceNamespace.SendSMSSoap.GetSMSNumbersAsync(SmsServiceNamespace.GetSMSNumbersRequest request)
        {
            return base.Channel.GetSMSNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceNamespace.GetSMSNumbersResponse> GetSMSNumbersAsync(string signature, int numberType, SmsServiceNamespace.ArrayOfString numbers)
        {
            SmsServiceNamespace.GetSMSNumbersRequest inValue = new SmsServiceNamespace.GetSMSNumbersRequest();
            inValue.Body = new SmsServiceNamespace.GetSMSNumbersRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.numberType = numberType;
            inValue.Body.numbers = numbers;
            return ((SmsServiceNamespace.SendSMSSoap)(this)).GetSMSNumbersAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SendSMSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SendSMSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SendSMSSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://login.parsgreen.com/Api/SendSMS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SendSMSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://login.parsgreen.com/Api/SendSMS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SendSMSSoap,
            
            SendSMSSoap12,
        }
    }
}
